baseURL: https://faerieringgames.netlify.app
title: Faerie ring games
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 6
enableEmoji: true
services:
  disqus: {}
markup:
  highlight:
    noClasses: false
params:
  author: Faerie Ring Games
  description: Faerie Ring Games
  keywords: go,design,card
  info:
    - Abstract Strategy Games
  avatarURL: images/frg_logo_small.png
  dateFormat: January 2, 2006
  since: 2024
  commit: https://github.com/luizdepra/hugo-coder/tree/
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []
  customRemoteJS: []
  social:
    - name: Trello
      icon: fa-brands fa-trello
      weight: 1
      url: https://faerieringgames.netlify.app/trello
    - name: Trello
      icon: fa-brands fa-discord
      weight: 1
      url: https://faerieringgames.netlify.app/discord
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        - name: Games
          weight: 1
          url: games/
        - name: Blog
          weight: 2
          url: posts/
        - name: About
          weight: 3
          url: about/
        - name: Contact me
          weight: 5
          url: contact/