---
# to edit the theme colors edit the file
# .\themes\hugo-coder\assets\scss\_variables.scss
baseURL: https://faerieringgames.com
title: Faerie ring games
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
pagination.pagerSize: 6
enableEmoji: true
services:
  disqus: {}
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
params:
  author: Faerie Ring Games
  description: Faerie Ring Games
  keywords: go,design,card
  info:
    - Abstract Strategy Games
  avatarURL: images/faerieringgames_logo.gif
  dateFormat: January 2, 2006
  since: 2024
  commit: https://github.com/luizdepra/hugo-coder/tree/
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []
  customRemoteJS: []
  social:
    - name: Trello
      icon: fa-brands fa-trello
      weight: 1
      url: https://faerieringgames.com/trello
    - name: Discord
      icon: fa-brands fa-discord
      weight: 2
      url: https://faerieringgames.com/discord
    - name: Github
      icon: fa-brands fa-github
      weight: 3
      url: https://github.com/RunielN597/faerieringgames
    - name: Youtube
      icon: fab fa-youtube
      weight: 4
      url: https://faerieringgames.com/youtube
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        - name: Games
          weight: 1
          url: games/
        - name: Blog
          weight: 2
          url: posts/
        - name: About
          weight: 3
          url: about/
        - name: Contact me
          weight: 5
          url: contact/
